# Generated by Django 4.1 on 2022-10-10 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
