# Generated by Django 4.1 on 2022-10-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_daily_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='nuber_in_stock',
            new_name='number_in_stock',
        ),
    ]
