# Generated by Django 4.1 on 2022-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_nuber_in_stock_book_number_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='manga_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
